=================
BUILD
=================

1. UBUNTU

In order to build this project under Ubuntu 14.04 LTS, execute the following commands in this directory:

$ make release

You can also choose to execute 'make debug' if you want debug output and symbols.

If you're building this project for the first time, make sure the directory ../build exists by executing this first:
$ mkdir ../build

The resulting executable will be called multipong and found in ../build.

2. WINDOWS

(Code::Blocks)

3. MAC OS X

You can try with the make command from ubuntu, but it's untested.
