=================
BUILD
=================

1. UBUNTU

A ============ PREREQUISITES

In order to build this project under Ubuntu 14.04 LTS, you need to meet some prerequisites. First install the following libraries from the locations listed below:

GNU gcc, GNU make from their website if you don't have them already.
SDL2		https://www.libsdl.org/
SDL_ttf		https://www.libsdl.org/projects/SDL_ttf/
SDL_net		https://www.libsdl.org/projects/SDL_net/
SDL_image	https://www.libsdl.org/projects/SDL_image/

The three latter libraries can be installed by downloading the .tar.gz from the website, unpacking it and then executing:

$ ./configure
$ make
$ sudo make install

B ============ BUILDING FOR THE FIRST TIME

If you're building this project for the first time, make sure the directories ../build, ../build/release and ../build/debug exist by going into this directory in the terminal and executing this first:

$ mkdir ../build
$ mkdir ../build/release
$ mkdir ../build/debug

C ============ REGULAR BUILDS

After you have successfully installed the libraries and created the directories, you should be able to execute the following commands in this directory:

$ make release

You can also choose to execute 'make debug' if you want debug output and symbols.

D ============ EXECUTING THE PROGRAM

The resulting executable will be called multipong and found in ../build/release or ../build/debug. You can also execute them by running either of:

$ make execute_release
$ make execute_debug

2. WINDOWS

(Code::Blocks)

3. MAC OS X

See the manual for ubuntu. Maybe it works.
