=================
BUILD
=================

1. UBUNTU

In order to build this project under Ubuntu 14.04 LTS, execute the following commands in this directory:

$ make release

You can also choose to execute 'make debug' if you want debug output and symbols.

If you're building this project for the first time, make sure the directories ../build, ../build/release and ../build/debug exist by executing this first:
$ mkdir ../build
$ mkdir ../build/release
$ mkdir ../build/debug

The resulting executable will be called multipong and found in ../build/release or ../build/debug.

2. WINDOWS

(Code::Blocks)

3. MAC OS X

You can try with the make command from ubuntu, but it's untested.
